from typing import Any, Dict


class ValidatorService:
    """
    Validates an Agent Specification generated by the Agent Builder.

    This service is migrated from the original AI Layer validator.
    It intentionally preserves the original validation rules:
    - name
    - description
    - capabilities
    - system prompt
    - model configuration
    - input schema
    - output schema
    """

    def validate(self, spec: Dict[str, Any]) -> dict:
        errors = []
        warnings = []

        # Validate name
        name = spec.get("name")

        if not name or not str(name).strip():
            errors.append("Agent name is required")
        elif len(str(name).strip()) < 3:
            errors.append("Agent name must be at least 3 characters")

        # Validate description
        description = spec.get("description")

        if not description or not str(description).strip():
            errors.append("Agent description is required")

        # Validate capabilities
        capabilities = spec.get("capabilities")

        if not capabilities or len(capabilities) == 0:
            errors.append("Agent must have at least one capability")

        # Validate system prompt
        system_prompt = spec.get("system_prompt")

        if not system_prompt or not str(system_prompt).strip():
            errors.append("System prompt is required")
        elif len(str(system_prompt).strip()) < 20:
            warnings.append(
                "System prompt is very short, consider making it more detailed"
            )

        # Validate model
        model = spec.get("model")

        if not model:
            errors.append("Model configuration is required")
        else:
            provider = model.get("provider")
            model_name = model.get("model")

            if not provider:
                errors.append("Model provider is required")

            if not model_name:
                errors.append("Model name is required")

        # Validate input schema
        input_schema = spec.get("input_schema")

        if not input_schema:
            warnings.append(
                "Input schema is empty, consider defining expected inputs"
            )

        # Validate output schema
        output_schema = spec.get("output_schema")

        if not output_schema:
            warnings.append(
                "Output schema is empty, consider defining expected outputs"
            )

        is_valid = len(errors) == 0

        return {
            "valid": is_valid,
            "errors": errors,
            "warnings": warnings,
            "spec": spec if is_valid else None,
        }


validator_service = ValidatorService()
